import type { JourneyItem, ProjectItem, ProofItem, StudentProfile } from './types'

export const DEFAULT_PROFILE: StudentProfile = {
  name: 'Kiran Raj M',
  photo:
    'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=88',
  department: 'Artificial Intelligence & Data Science',
  year: '2nd Year',
  college: 'Sri Venkateswara College of Engineering',
  role: 'Student Developer / AI & Data Science',
  foreseRole: 'Member',
  bio: 'I turn curious questions into useful systems — exploring machine intelligence, expressive interfaces, and the quiet details that make software feel human.',
  skills: [
    'C++',
    'Python',
    'JavaScript',
    'TypeScript',
    'React',
    'Vite',
    'HTML/CSS',
    'Tailwind CSS',
    'Node.js',
    'FastAPI',
    'REST APIs',
    'SQL',
    'Git/GitHub',
    'Machine Learning',
    'Deep Learning',
    'NLP',
    'Computer Vision',
  ],
  instagram: 'https://www.instagram.com/kiran_archer/',
  github: 'https://github.com/Kiran007734',
  linkedin: '',
  email: 'kiranrajxarcher.2008@gmail.com',
  phone: '9445438297',
}

export const JOURNEY: JourneyItem[] = [
  {
    year: 'NOW',
    title: 'B.Tech — Artificial Intelligence & Data Science',
    description: 'Learning to move fluently between data, models, and the products they power.',
    label: '01 / STUDY',
  },
  {
    year: '2025',
    title: 'Technical Executive — FODSE',
    description: 'Helping a student community turn ambitious ideas into thoughtful digital work.',
    label: '02 / COMMUNITY',
  },
  {
    year: '2025',
    title: 'Techie — Marketing & Communications Club',
    description: 'Exploring the overlap between clear storytelling, visual systems, and technology.',
    label: '03 / COLLABORATE',
  },
  {
    year: 'ONGOING',
    title: 'Hackathons / AI experiments',
    description: 'Building quickly, testing honestly, and keeping a notebook full of better questions.',
    label: '04 / MAKE',
  },
]

export const PROJECTS: ProjectItem[] = [
  {
    id: 'codepulse',
    number: '01',
    name: 'CodePulse',
    description: 'AI-driven developer intelligence platform for understanding how teams turn requirements into working software.',
    detail: 'CodePulse connects contribution intelligence with requirement-to-code mapping, skill intelligence, knowledge risk, functional impact, and AI recommendations.',
    category: 'DEVELOPER INTELLIGENCE',
    stack: 'AI · GRAPH ANALYSIS · REACT',
    focus: ['Contribution intelligence', 'Requirement mapping', 'Knowledge risk', 'AI recommendations'],
    visual: 'CP',
    accent: 'coral',
  },
  {
    id: 'parkverse-ai',
    number: '02',
    name: 'ParkVerse AI',
    description: 'AI-powered decentralized parking platform built around prediction, trust, and less time spent searching.',
    detail: 'ParkVerse AI brings together predictive analytics, computer vision, dynamic pricing, a conversational assistant, and Razorpay integration.',
    category: 'SMART INFRASTRUCTURE',
    stack: 'AI · COMPUTER VISION · RAZORPAY',
    focus: ['Predictive analytics', 'Computer vision', 'Dynamic pricing', 'Chatbot'],
    visual: 'PV',
    accent: 'olive',
  },
  {
    id: 'fraudshield',
    number: '03',
    name: 'FraudShield Gateway',
    description: 'Real-time banking fraud prevention and authorization platform for decisions that can be explained.',
    detail: 'FraudShield combines behavioral, device, location, velocity, and graph intelligence to make fraud decisions more transparent at the moment they matter.',
    category: 'FINTECH / SECURITY',
    stack: 'PYTHON · ML · FASTAPI',
    focus: ['Behavioral analysis', 'Anomaly detection', 'Device intelligence', 'Explainable decisions'],
    href: 'https://github.com/Kiran007734/Fraudshield',
    visual: 'FS',
    accent: 'blue',
  },
  {
    id: 'retina-nexus',
    number: '04',
    name: 'Retina-Nexus',
    description: 'Explainable AI platform for early diabetic retinopathy screening and intelligent triage.',
    detail: 'Retina-Nexus uses a retinal image quality gate, coarse-to-fine AI, Grad-CAM evidence, and RetinaGuard to support clinical review without hiding the reasoning.',
    category: 'HEALTHCARE / AI',
    stack: 'PYTHON · COMPUTER VISION · XAI',
    focus: ['Image quality gate', 'Coarse-to-fine AI', 'Grad-CAM evidence', 'Intelligent triage'],
    href: 'https://github.com/Kiran007734/retina_nexus',
    visual: 'RN',
    accent: 'coral',
  },
  {
    id: 'flow',
    number: '05',
    name: 'Flow',
    description: 'Treasury Management Platform that makes the movement of money easier to see and act on.',
    detail: 'Flow is a focused treasury management experience for turning financial operations into a clear, navigable daily rhythm.',
    category: 'FINTECH / PRODUCT',
    stack: 'REACT · TYPESCRIPT · DATA',
    focus: ['Cash visibility', 'Treasury workflows', 'Decision support', 'Operations'],
    href: 'https://github.com/Kiran007734/Treasurey_management_platform',
    visual: 'FL',
    accent: 'olive',
  },
  {
    id: 'mcc-website',
    number: '06',
    name: 'MCC Website',
    description: 'Marketing & Communications Club website designed to give student work a confident public stage.',
    detail: 'A club website built around clear storytelling, event discovery, and the visual energy of a student-led creative community.',
    category: 'WEB / COMMUNITY',
    stack: 'REACT · VITE · UI',
    focus: ['Editorial storytelling', 'Event discovery', 'Club identity', 'Responsive UI'],
    href: 'https://github.com/Kiran007734/mcc_website',
    visual: 'MC',
    accent: 'blue',
  },
  {
    id: 'fodse-website',
    number: '07',
    name: 'FODSE Website',
    description: 'FODSE Club website for bringing technical community, announcements, and opportunities together.',
    detail: 'A flexible student-community site that gives FODSE a clear digital home for its people, projects, and next events.',
    category: 'WEB / COMMUNITY',
    stack: 'REACT · TYPESCRIPT · DESIGN',
    focus: ['Community building', 'Announcements', 'Project showcase', 'Interaction design'],
    href: 'https://github.com/Kiran007734/Fodse_website',
    visual: 'FO',
    accent: 'coral',
  },
]

export const PROOF_ITEMS: ProofItem[] = [
  { label: 'AI / 01', title: 'Intelligent systems', detail: 'FraudShield · Retina-Nexus · ParkVerse AI' },
  { label: 'WEB / 02', title: 'Club websites', detail: 'MCC Website · FODSE Website' },
  { label: 'MAKE / 03', title: 'Hackathons & experiments', detail: 'Fast prototypes, honest iterations, useful outcomes' },
  { label: 'SHIP / 04', title: 'Technical work', detail: 'Interfaces, APIs, data models, and the details between' },
]
